steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/$PROJECT_ID/kiddo/kiddo-backend:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/$PROJECT_ID/kiddo/kiddo-backend:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'kiddo-backend'
      - '--image=asia-south1-docker.pkg.dev/$PROJECT_ID/kiddo/kiddo-backend:latest'
      - '--platform=managed'
      - '--region=asia-south1'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--timeout=300'
      - '--set-env-vars=^;^NODE_ENV=production;CLIENT_ORIGIN=https://kiddoapp.in,https://www.kiddoapp.in;FIREBASE_PROJECT_ID=kiddo-bf68d'
      - '--set-secrets=MONGODB_URI=mongodb-uri:latest,JWT_ACCESS_SECRET=jwt-access-secret:latest,JWT_REFRESH_SECRET=jwt-refresh-secret:latest,FIREBASE_SERVICE_ACCOUNT_KEY=firebase-service-account-key:latest'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/kiddo/kiddo-backend:latest'
