import { Schema, model } from 'mongoose';
import { ROLES } from '../constants/roles.js';

const userSchema = new Schema(
  {
    familyId: { type: Schema.Types.ObjectId, ref: 'Family' },
    parentId: { type: Schema.Types.ObjectId, ref: 'User' },
    role: { type: String, enum: Object.values(ROLES), required: true },
    email: { type: String, trim: true, lowercase: true, sparse: true, unique: true },
    firebaseUid: { type: String, trim: true, sparse: true, unique: true },
    username: { type: String, trim: true, lowercase: true, sparse: true, unique: true },
    passwordHash: { type: String },
    childLoginCode: { type: String, trim: true, uppercase: true, sparse: true, unique: true },
    firstName: { type: String, required: true, trim: true },
    lastName: { type: String, trim: true, default: '' },
    standard: { type: Number, min: 1, max: 12, default: 1 },
    school: { type: String, trim: true, default: '' },
    avatar: { type: String, default: 'rocket-kid' },
    points: { type: Number, default: 0 },
    streak: { type: Number, default: 0 },
    xp: { type: Number, default: 0 },
    level: { type: Number, default: 1 },
    skillXP: {
      intelligence: { type: Number, default: 0 },
      strength: { type: Number, default: 0 },
      kindness: { type: Number, default: 0 },
    },
    chessWins: { type: Number, default: 0 },
    chessGamesPlayed: { type: Number, default: 0 },
    lastChessRewardAt: { type: Date },
    memoryWins: { type: Number, default: 0 },
    memoryGamesPlayed: { type: Number, default: 0 },
    lastMemoryRewardAt: { type: Date },
    mathWins: { type: Number, default: 0 },
    mathGamesPlayed: { type: Number, default: 0 },
    lastMathRewardAt: { type: Date },
    patternWins: { type: Number, default: 0 },
    patternGamesPlayed: { type: Number, default: 0 },
    lastPatternRewardAt: { type: Date },
    puzzleWins: { type: Number, default: 0 },
    puzzleGamesPlayed: { type: Number, default: 0 },
    lastPuzzleRewardAt: { type: Date },
    lastCompletedAt: { type: Date },
    notificationToken: { type: String },
    isActive: { type: Boolean, default: true },
    schoolName: { type: String, trim: true, default: '' },
    teacherId: { type: Schema.Types.ObjectId, ref: 'Teacher' },
    classId: { type: Schema.Types.ObjectId, ref: 'Class' },
    gender: { type: String, enum: ['male', 'female', 'other'], default: 'male' },
    settings: {
      animationsEnabled: { type: Boolean, default: true },
      badgesEnabled: { type: Boolean, default: true },
      avatarCustomization: { type: Boolean, default: true },
      taskAlerts: { type: Boolean, default: true },
      weeklySummary: { type: Boolean, default: true },
      reminderNotifications: { type: Boolean, default: true },
      quietHours: { type: Boolean, default: true },
      lockAppAccess: { type: Boolean, default: false },
      whatsappSummary: { type: Boolean, default: false },
      emailSummary: { type: Boolean, default: true },
      language: { type: String, default: 'en-IN' },
      currentTheme: { type: String, default: 'space' },
      conversionAlerts: { type: Boolean, default: true },
      purchaseAlerts: { type: Boolean, default: true },
      rewardAlerts: { type: Boolean, default: true },
      campaignAlerts: { type: Boolean, default: true },
      giftAlerts: { type: Boolean, default: true },
    },
    weeklySchedule: {
      monday: { type: Boolean, default: true },
      tuesday: { type: Boolean, default: true },
      wednesday: { type: Boolean, default: true },
      thursday: { type: Boolean, default: true },
      friday: { type: Boolean, default: true },
      saturday: { type: Boolean, default: false },
      sunday: { type: Boolean, default: false },
    },
    wakeUpSettings: {
      targetTime: { type: String, default: '06:30' },
      mandatory: { type: Boolean, default: true },
    },
    inventory: [{ type: Schema.Types.ObjectId, ref: 'ShopItem' }],
    equipped: {
      hat: { type: Schema.Types.ObjectId, ref: 'ShopItem' },
      cape: { type: Schema.Types.ObjectId, ref: 'ShopItem' },
      glasses: { type: Schema.Types.ObjectId, ref: 'ShopItem' },
      pet: { type: Schema.Types.ObjectId, ref: 'ShopItem' },
      suit: { type: Schema.Types.ObjectId, ref: 'ShopItem' },
      background: { type: Schema.Types.ObjectId, ref: 'ShopItem' },
    },
    obtainedRewards: [{
      rewardId: { type: Schema.Types.ObjectId, ref: 'Reward' },
      title: String,
      redeemedAt: { type: Date, default: Date.now },
      pointsSpent: Number,
    }],
    achievements: [{
      achievementId: { type: Schema.Types.ObjectId, ref: 'AchievementDefinition' },
      progress: { type: Number, default: 0 },
      target: { type: Number, default: 1 },
      unlockedAt: { type: Date },
      notified: { type: Boolean, default: false },
    }],
    badges: [{
      badgeId: { type: Schema.Types.ObjectId, ref: 'BadgeDefinition' },
      unlockedAt: { type: Date, default: Date.now },
      notified: { type: Boolean, default: false },
    }],
    challenges: [{
      challengeId: { type: Schema.Types.ObjectId, ref: 'Challenge' },
      progress: { type: Number, default: 0 },
      target: { type: Number, default: 1 },
      status: { type: String, enum: ['active', 'claimed', 'expired'], default: 'active' },
      claimedAt: { type: Date },
    }],
    completedMissions: [{
      missionId: { type: Schema.Types.ObjectId, ref: 'MissionDefinition' },
      completedAt: { type: Date, default: Date.now },
    }],
    completedMilestones: [{
      milestoneId: { type: Schema.Types.ObjectId, ref: 'MilestoneDefinition' },
      completedAt: { type: Date, default: Date.now },
    }],
    lastLoginDate: { type: Date },
    loginStreakCount: { type: Number, default: 0 },
    lastScrollAt: { type: Date },
  },
  { timestamps: true },
);

export const User = model('User', userSchema);
